# Generated by Django 4.2.6 on 2023-10-31 18:28

from django.db import migrations
import image_optimizer.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_tag_post_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=image_optimizer.fields.OptimizedImageField(upload_to='photos/blog'),
        ),
    ]
