# Generated by Django 5.0 on 2024-06-16 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0002_account_recovery_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='recovery_phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
